add about page styling
ooug/odishaoug.in pull request #96
Opened 2021-04-30 13:49 UTC by jashwant1234

change some style.
![Screenshot (12)](https://user-images.githubusercontent.com/46989904/116704301-1a795780-a980-11eb-9596-28f497a23529.png)
![Screenshot (13)](https://user-images.githubusercontent.com/46989904/116704317-1cdbb180-a980-11eb-94bf-0c8a7ed4862e.png)

2021-04-30 15:39 UTC, InSantoshMahto requested changes
do not change any editor config

2021-04-30 15:39 UTC, InSantoshMahto commented on .vscode/settings.json
> +  "files.autoSave": "off",
set this like `"files.autoSave": "onWindowChange",`

2021-04-30 15:45 UTC, jashwant1234 commented on .vscode/settings.json
> +  "files.autoSave": "off",
ohk

2021-05-01 06:51 UTC, InSantoshMahto approved these changes

2021-05-01 06:51 UTC, merged